---
title: Cord Docs
timezone: UTC
collections:
  api:
    title: API
    output: true
  colours:
    title: Colours
    output: true
  guides:
    title: Guides
    output: true
  navigation:
    title: Navigation
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: guides
  values:
    Colours:
    Icon:
    Overview Description:
    Introduction Text:
    Sections:
    - Title: 
      Text:
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/docs"
url: https://blongden73.github.io
twitter_username: jekyllrb
github_username: jekyll
theme: minima
sass:
  sass_dir: "./_scss"
plugins:
- jekyll-feed
